### ISSUE TITLE
Maven Central is Behind the GitHub Release Tags and Contains Releases that GitHub doesn't have Release Tags for.

### ISSUE THREAD

**Issue by josiah14** [urbanairship/connect-java-library#3]
The [Maven Central Repository](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.urbanairship%22%20AND%20a%3A%22connect-client%22) doesn't match the [Release Tags](https://github.com/urbanairship/connect-java-library/releases) in this GitHub repository.

The latest Release in Maven is [3.0.0](https://search.maven.org/#artifactdetails%7Ccom.urbanairship%7Cconnect-client%7C3.0.0%7Cjar) and was uploaded on June 6th, 2016.  There appear to have been major revisions made to the library's/client's interface and significant error reporting enhancements made since that time, judging from the commit messages (but not taking a closer look into the diffs).  The GitHub repository does not have a Release Tag for 3.0.0, but you can see the [commit](https://github.com/urbanairship/connect-java-library/commit/242f347453fec8d263bc473623e89d0eabbe2ff0) which bumped the code to that version on June 6th.

As long as the README is suggesting that Maven can be used to grab this library as a dependency, Maven Central ought to be up-to-date with the latest releases, not more than a year behind on a release with a very different looking interface.

**Comment by josiah14** [comment]
FYI, this can be manually worked around by cloning the GitHub repository from the Release Tag you want (or downloading the .tar.gz archive and extracting it), changing the `maven-enforcer-plugin` version to not have the `-ua1.0` appended to it in the `pom.xml` (see issue #4 ), running `mvn package && mvn javadoc:javadoc` and then copying all of the jars in `target/` and the `pom.xml` and its sha1 hash to the Maven cache in `.ivy2/cache/`, or if you are using SBT with Coursier, the cache is at ~/.coursier/cache/v1/https/repo1.maven.org/maven2/`

**Comment by josiah14** [comment]
@gatlinhebert informed me that JFrog Bintray is used, now, to host releases of this library.  As long as that is the case, it should be clearly documented that Bintray is being used so that developers know they need to point their build tools (Leiningen, SBT, Maven, Gradle, ...) to JFrog Bintray.

For SBT, you would use the [sbt-bintray plugin](https://github.com/sbt/sbt-bintray)
For Maven, [the instructions](https://bintray.com/docs/usermanual/formats/formats_mavenrepositories.html#anchorMavenResolve) are on the JFrog website.

**Comment by aschuman0** [comment]
We have updated the maven central repository with the most up-to-date version. Apologies for the time it has taken to make this update. Our internal process has changed so that this will stay in sync in the future.
