### ISSUE TITLE
Exceptions Thrown from the Library Don't Get Passed to the Library Consumer App

### ISSUE THREAD

**Issue by josiah14** [urbanairship/connect-java-library#6]
It appears that all of the non-200/300 statuses (402, 404, 500+ codes) trigger the same Exception in the Urban Airship Java Connect library, and that the exception is printed to stderr or stdout by the library and not thrown back up to application using the library.  This means that we have no way of telling 402, 404, 500, 502, etc apart (even from the logs produced by the library itself), or delegating to different execution flows/code based on those statuses. As an illustration, when I couldn't connect to the stream because of Java's built-in encryption strength limits, I just got back a generic java.util.RuntimeException  which said that max number of reconnect attempts had been exceeded.

Below is a summary of my trace and investigation into what was going on.

https://github.com/urbanairship/connect-java-library/blob/master/src/main/java/com/urbanairship/connect/client/HttpClientUtil.java#L23

https://github.com/urbanairship/connect-java-library/blob/master/src/main/java/com/urbanairship/connect/client/StreamConsumeTask.java#L265 

The below line of code is what produces the error message I received.  It just wraps the Exception in a generic RuntimeException with a generic message but doesn't pass it back ([defaultExceptionHandler is not utilized](https://github.com/urbanairship/connect-java-library/search?utf8=%E2%9C%93&q=setDefaultExceptionHandler&type=) and the [Exceptions from the ExecutorService aren't rethrown](https://github.com/urbanairship/connect-java-library/blob/dd8844cfdc978f387af184054d53491ab7a9db45/src/main/java/com/urbanairship/connect/client/Stream.java#L140) for the library consumer to have access to them) to the application to allow the consumer of the library to handle.  [The exceptions ARE being chained, however](https://github.com/urbanairship/connect-java-library/blob/master/src/main/java/com/urbanairship/connect/client/StreamConnection.java#L141), and the ExecutorService class IS being utilized, so there's code in place that could facilitate easily creating a better Exception handling policy, but at present, the library [only prints out the top level Exception on the Exception Chain, which is the most generic one](https://github.com/urbanairship/connect-java-library/blob/master/src/main/java/com/urbanairship/connect/client/StreamConsumeTask.java#L113).

https://github.com/urbanairship/connect-java-library/blob/master/src/main/java/com/urbanairship/connect/client/StreamConnection.java#L137

**Comment by josiah14** [comment]
Correct me if I'm wrong about how things are working, but hopefully the links to all the code are enough to prove I did my due diligence before submitting this ticket.

**Comment by aschuman0** [comment]
This should be corrected in version 4.1.3
